const MESSAGES = {
    COMMANDS: {
        ADMIN: {
            CONFIG: {
                name: 'config',
                aliases: ['config'],
                category: 'admin',
                description: 'Modifier la base de données',
                cooldown: 3,
                usage: '<key> <value>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            EVAL: {
                name: 'eval',
                aliases: ['eval'],
                category: 'admin',
                description: 'Renvoie un code javascript testé',
                cooldown: 3,
                usage: '<code_to_test>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            RELOAD: {
                name: 'reload',
                aliases: ['reload'],
                category: 'admin',
                description: 'Redémarrez le bot',
                cooldown: 3,
                usage: '',
                isUserAdmin: false,
                permissions: true,
                args: false,
            },
            SLEEP: {
                name: 'sleep',
                aliases: ['sleep'],
                category: 'admin',
                description: 'Eteindre le bot',
                cooldown: 3,
                usage: '',
                isUserAdmin: false,
                permissions: true,
                args: false,
            },
        },
        COLLECTORS: {
            MSGCOLLECTOR: {
                name: 'msgcollector',
                aliases: ['msgcollector', 'mcol'],
                category: 'collectors',
                description: 'Message collector',
                cooldown: 3,
                usage: '<message_to_collect>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            REACTCOLLECTOR: {
                name: 'reactcollector',
                aliases: ['reactcollector', 'rcol'],
                category: 'collectors',
                description: 'React collector',
                cooldown: 3,
                usage: '',
                isUserAdmin: false,
                permissions: true,
                args: false,
            },
        },
        EXPERIENCE: {
            ADDEXPERIENCE: {
                name: 'addexperience',
                aliases: ['addexperience', 'addexp', 'aexp'],
                category: 'experience',
                description: 'Ajoute de l\'expérience à l\'utilisateur',
                cooldown: 10,
                usage: '@user <exp_to_add>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            LEADERBOARD: {
                name: 'leaderboard',
                aliases: ['leaderboard', 'leader', 'board', 'lb', 'classement'],
                category: 'experience',
                description: 'Affiche le leaderboard top de l\'expérience des utilisateurs sur le serveur',
                cooldown: 10,
                usage: '',
                isUserAdmin: false,
                permissions: true,
                args: false,
            },
            REMOVEEXPERIENCE: {
                name: 'removeexperience',
                aliases: ['removeexperience', 'removeexp', 'rmexp', 'rexp'],
                category: 'experience',
                description: 'Retire de l\'expérience à l\'utilisateur',
                cooldown: 10,
                usage: '@user <exp_to_remove>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            USEREXPERIENCE: {
                name: 'experience',
                aliases: ['experience', 'exp'],
                category: 'experience',
                description: 'Renvoie l\'expérience de l\'utilisateur',
                cooldown: 3,
                usage: '@user',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
        },
        GAMES: {
            EIGHTBALL: {
                name: '8ball',
                aliases: ['8ball', 'question', 'q'],
                category: 'games',
                description: 'Renvoie une réponse à une question',
                cooldown: 4,
                usage: '<question>',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            DICE: {
                name: 'dice',
                aliases: ['dé', 'de', '421'],
                category: 'games',
                description: 'Lance 3 dé aléatoirement',
                cooldown: 10,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
        },
        MISCELLANEOUS: {
            ABOUT: {
                name: 'about',
                aliases: ['about', 'desc', 'description'],
                category: 'miscellaneous',
                description: 'Si vous utilisez cette commande, Yumeko se présentera!',
                cooldown: 30,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            AVATAR: {
                name: 'avatar',
                aliases: ['avatar', 'a'],
                category: 'miscellaneous',
                description: 'Renvoie la photo de profil de l\'utilisateur mentionnée, si personne n\'est mentionné, vous envoie votre photo de profil',
                cooldown: 5,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            SAY: {
                name: 'say',
                aliases: ['repeat', 'rep'],
                category: 'miscellaneous',
                description: 'Répète le message d\'un utilisateur',
                cooldown: 30,
                usage: 'Hello World',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            PING: {
                name: 'ping',
                aliases: ['ping'],
                category: 'miscellaneous',
                description: 'Renvoie le ping de la personne executant la commande',
                cooldown: 30,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            POLL: {
                name: 'poll',
                aliases: ['poll'],
                category: 'miscellaneous',
                description: 'Créé un sondage',
                cooldown: 10,
                usage: '<sondage>',
                isUserAdmin: false,
                permissions: false,
                args: true,
            },
            HELP: {
                name: 'help',
                aliases: ['help'],
                category: 'miscellaneous',
                description: 'Vous envoie toute l\'aide nécessaire de toutes les commandes disponibles avec le bot 蛇喰 夢子, mais ça tu le sais déjà ^^',
                cooldown: 10,
                usage: '<command_name>',
                isUserAdmin: false,
                permissions: true,
                args: false,
            },
            STATS: {
                name: 'stats',
                aliases: ['stats'],
                category: 'miscellaneous',
                description: 'Vous envoie des statistiques du serveur ou de la personne mentionnée',
                cooldown: 3,
                usage: 'ou ?stats @user',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
        },
        MODERATION: {
            BAN: {
                name: 'ban',
                aliases: ['ban'],
                category: 'moderation',
                description: 'Banni l\'utilisateur mentionné',
                cooldown: 1,
                usage: '@user',
                isUserAdmin: true,
                permissions: true,
                args: true,
            },
            KICK: {
                name: 'kick',
                aliases: ['kick'],
                category: 'moderation',
                description: 'Kick un utilisateur mentionné',
                cooldown: 1,
                usage: '@user',
                isUserAdmin: true,
                permissions: true,
                args: true,
            },
            MUTE: {
                name: 'mute',
                aliases: ['mute'],
                category: 'moderation',
                description: 'Mute un utilisateur mentionné',
                cooldown: 1,
                usage: '?mute @user <time> <reason>',
                isUserAdmin: true,
                permissions: true,
                args: true,
            },
            PRUNE: {
                name: 'prune',
                aliases: ['prune', 'uclear'],
                category: 'moderation',
                description: 'Supprime un nombre spécifié de messages sur un utilisateur précis dans le salon où la commande est réalisée',
                cooldown: 5,
                usage: '?prune <amount> <user_id>',
                isUserAdmin: true,
                permissions: true,
                args: true,
            },
            PURGE: {
                name: 'purge',
                aliases: ['purge', 'clear'],
                category: 'moderation',
                description: 'Supprime un nombre spécifié de messages dans le salon où la commande est réalisée',
                cooldown: 5,
                usage: '<amount>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            UNBAN: {
                name: 'unban',
                aliases: ['unban'],
                category: 'moderation',
                description: 'Débanni l\'utilisateur mentionné',
                cooldown: 1,
                usage: '<user_id>',
                isUserAdmin: false,
                permissions: true,
                args: true,
            },
            UNMUTE: {
                name: 'unmute',
                aliases: ['unmute'],
                category: 'moderation',
                description: 'Démute un utilisateur mentionné',
                cooldown: 1,
                usage: '<time> <reason>',
                isUserAdmin: true,
                permissions: true,
                args: true,
            },
        },
        RANDOMIMAGE: {
            ANIME: {
                name: 'anime',
                aliases: ['anime'],
                category: 'randomimage',
                description: 'Envoie une photo d\'animé aléatoire',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            AVATAR: {
                name: 'avatar',
                aliases: ['avatar'],
                category: 'randomimage',
                description: 'Envoie un avatar aléatoire',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            BAKA: {
                name: 'baka',
                aliases: ['baka'],
                category: 'randomimage',
                description: 'S\'énerve contre la personne mentionnée',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: true,
            },
            CAT: {
                name: 'cat',
                aliases: ['cat', 'chat'],
                category: 'randomimage',
                description: 'Envoie une photo de chat aléatoire',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            DOG: {
                name: 'dog',
                aliases: ['dog', 'chien'],
                category: 'randomimage',
                description: 'Envoie une photo de chien aléatoire',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            FOX: {
                name: 'fox',
                aliases: ['fox', 'renard'],
                category: 'randomimage',
                description: 'Envoie une photo de renard aléatoire',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            HUG: {
                name: 'hug',
                aliases: ['hug'],
                category: 'randomimage',
                description: 'Fais un câlin à la personne mentionnée',
                cooldown: 0,
                usage: '@user',
                isUserAdmin: false,
                permissions: false,
                args: true,
            },
            KISS: {
                name: 'kiss',
                aliases: ['kiss'],
                category: 'randomimage',
                description: 'Fais un bisou à la personne mentionnée!',
                cooldown: 0,
                usage: '@user',
                isUserAdmin: false,
                permissions: false,
                args: true,
            },
            POKE: {
                name: 'poke',
                aliases: ['poke'],
                category: 'randomimage',
                description: 'Poke la personne mentionnée!',
                cooldown: 0,
                usage: '@user',
                isUserAdmin: false,
                permissions: false,
                args: true,
            },
            SLAP: {
                name: 'slap',
                aliases: ['anime'],
                category: 'randomimage',
                description: 'Donne une claque à la personne mentionnée!',
                cooldown: 0,
                usage: '@user',
                isUserAdmin: false,
                permissions: false,
                args: true,
            },
            WAIFU: {
                name: 'waifu',
                aliases: ['waifu'],
                category: 'randomimage',
                description: 'Envoie un waifu aléatoire',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
            WALLPAPER: {
                name: 'wallpaper',
                aliases: ['wallpaper'],
                category: 'randomimage',
                description: 'Envoie un fond d\'écran aléatoire!',
                cooldown: 0,
                usage: '',
                isUserAdmin: false,
                permissions: false,
                args: false,
            },
        },
        REACTIONS: {
            AUTH: {
                name: 'auth',
                aliases: ['auth', 'auth'],
                category: 'reactions',
                description: 'Envoie un message de vérification avec une réaction sur le serveur',
                cooldown: 10,
                usage: '',
                isUserAdmin: false,
                permissions: true,
                args: false,
            },
        },
    }
}

exports.MESSAGES = MESSAGES